env:
  build_status_filename: build_status
  pr_id_key: pullrequestid
  run_id_key: runid
jobs:
  add_comment:
    if: ${{ github.repository == 'eclipse-leshan/leshan' && github.event.workflow_run.event
      == 'pull_request' && (github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion
      == 'failure')}}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download Build Status Archive
      uses: actions/github-script@v6.3.3
      with:
        script: "var artifacts = await github.rest.actions.listWorkflowRunArtifacts({\n\
          \   owner: context.repo.owner,\n   repo: context.repo.repo,\n   run_id:\
          \ ${{github.event.workflow_run.id }},\n});\nvar matchArtifact = artifacts.data.artifacts.filter((artifact)\
          \ => {\n  return artifact.name == '${{env.build_status_filename}}'\n})[0];\n\
          var download = await github.rest.actions.downloadArtifact({\n   owner: context.repo.owner,\n\
          \   repo: context.repo.repo,\n   artifact_id: matchArtifact.id,\n   archive_format:\
          \ 'zip',\n});\nvar fs = require('fs');\nfs.writeFileSync('${{github.workspace}}/${{env.build_status_filename}}.zip',\
          \ Buffer.from(download.data));\n"
    - continue-on-error: true
      name: Unzip Build Status Archive
      run: unzip ${{env.build_status_filename}}.zip
    - continue-on-error: true
      id: read_property
      name: Read Build Status Properties File
      uses: christian-draeger/read-properties@908f99d3334be3802ec7cb528395a69d19914e7b
      with:
        path: ${{env.build_status_filename}}
        properties: ${{env.pr_id_key}} ${{ matrix.jobstep }} ${{env.run_id_key}}
    - continue-on-error: true
      if: ${{ steps.read_property.outputs[matrix.jobstep] == 'failure'}}
      name: Download Add Comment Action
      uses: Bhacaz/checkout-files@e3e34e7daef91a5f237485bb88a260aee4be29dd
      with:
        files: .github/actions/utils/addcomment/action.yml
    - continue-on-error: true
      if: ${{ steps.read_property.outputs[matrix.jobstep] == 'failure'}}
      name: Add Comment on failure
      uses: ./.github/actions/utils/addcomment
      with:
        action_name: ${{ matrix.jobstep }}
        job_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{steps.read_property.outputs[env.run_id_key]}}
        pullrequest_id: ${{ steps.read_property.outputs[env.pr_id_key]}}
    - continue-on-error: true
      if: ${{ steps.read_property.outputs[matrix.jobstep] == 'success'}}
      name: Delete Comment on Success
      uses: marocchino/sticky-pull-request-comment@97bddef64db61b9d80edc69593cc4e4c415c3362
      with:
        delete: true
        header: ${{matrix.jobstep}}
        number: ${{ steps.read_property.outputs[env.pr_id_key]}}
    strategy:
      matrix:
        jobstep:
        - nomerge
        - sortpom
        - formatter
        - build
        - sortimport
        - checkstyle
        - androidcheck
        - semvercheck
        - javadoc
        - unittests
        - integrationtests
        - buildstatus
name: Comment Pull Request
on:
  repository_dispatch:
    types: trigger-ga___commentPR.yml
permissions:
  pull-requests: write
