jobs:
  del_runs:
    permissions:
      actions: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@c1a2f0de3fa4134a2357de83c92acff6e298bb8a
      with:
        keep_minimum_runs: 6
        repository: ${{ github.repository }}
        retain_days: 30
        token: ${{ github.token }}
name: Delete old workflow runs
on:
  repository_dispatch:
    types: trigger-ga___delete_workflow.yml
