jobs:
  dependency:
    if: github.repository == 'eclipse-leshan/leshan'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - continue-on-error: true
      name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@fcd7eab6b6d22946badc98d1e62665cdee93e0ae
name: Dependency Update
on:
  repository_dispatch:
    types: trigger-ga___dependency-update.yml
permissions:
  contents: write
