env:
  build_status_filename: build_status
  build_status_key: buildstatus
  pr_id_key: pullrequestid
  run_id_key: runid
jobs:
  build:
    if: github.repository == 'eclipse-leshan/leshan' && github.event.pull_request.draft
      == false
    name: Code Check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      id: nomerge
      name: Check No Merge Commit
      uses: ./.github/actions/nomerge
      with:
        build_status_filename: ${{env.build_status_filename}}
    - continue-on-error: true
      id: sortpom
      if: always()
      name: POM Format Check
      uses: ./.github/actions/sortpom
      with:
        build_status_filename: ${{env.build_status_filename}}
    - continue-on-error: true
      id: formatter
      if: always()
      name: Code Format Check
      uses: ./.github/actions/formatter
      with:
        build_status_filename: ${{env.build_status_filename}}
    - continue-on-error: true
      id: build
      if: always()
      name: Build
      uses: ./.github/actions/build
      with:
        build_status_filename: ${{env.build_status_filename}}
    - continue-on-error: true
      id: sortimport
      if: ${{ always() && steps.build.conclusion == 'success' }}
      name: Java Import Check
      uses: ./.github/actions/sortimport
      with:
        build_status_filename: ${{env.build_status_filename}}
    - continue-on-error: true
      id: checkstyle
      if: ${{ always() && steps.build.conclusion == 'success' }}
      name: Code Style Check
      uses: ./.github/actions/checkstyle
      with:
        build_status_filename: ${{env.build_status_filename}}
    - continue-on-error: true
      id: androidcheck
      if: ${{ always() && steps.build.conclusion == 'success' }}
      name: Check Android API Compliance
      uses: ./.github/actions/androidcheck
      with:
        build_status_filename: ${{env.build_status_filename}}
    - continue-on-error: true
      id: semvercheck
      if: ${{ always() && steps.build.conclusion == 'success' }}
      name: Check Semantic Versioning Compliance
      uses: ./.github/actions/semvercheck
      with:
        build_status_filename: ${{env.build_status_filename}}
    - continue-on-error: true
      id: javadoc
      if: ${{ always() && steps.build.conclusion == 'success' }}
      name: Generate Javadoc
      uses: ./.github/actions/javadoc
      with:
        build_status_filename: ${{env.build_status_filename}}
    - continue-on-error: true
      id: unittests
      if: ${{ always() &&  steps.build.conclusion == 'success' }}
      name: Unit Tests
      uses: ./.github/actions/unittests
      with:
        build_status_filename: ${{env.build_status_filename}}
    - continue-on-error: true
      id: integrationtests
      if: ${{ always() && steps.build.conclusion == 'success' }}
      name: Integration Tests
      uses: ./.github/actions/integrationtests
      with:
        build_status_filename: ${{env.build_status_filename}}
    - continue-on-error: true
      if: always()
      name: Store Variables for "Comment Pull Request" Workflow
      uses: GuillaumeFalourd/write-java-properties-file@c6762204aa02d62718ed285bca4cbcc400c65a10
      with:
        file_path: ${{env.build_status_filename}}
        property: '${{env.pr_id_key}}

          ${{env.run_id_key}}

          ${{env.build_status_key}}

          '
        value: '${{ github.event.number }}

          ${{ github.run_id }}

          ${{ job.status }}

          '
    - continue-on-error: true
      if: always()
      name: Upload Build Status File for "Comment Pull Request" Workflow
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.build_status_filename}}
        path: ${{env.build_status_filename}}
name: Check Pull Request
on:
  repository_dispatch:
    types: trigger-ga___main.yml
permissions: {}
